language: swift # or objective-c
osx_image: xcode9.2
script:
  - xcodebuild -scheme LongPomo -project LongPomo/LongPomo.xcodeproj -sdk macosx  -configuration Debug -enableCodeCoverage YES build test
  - xcodebuild -scheme LongPomo-ios -project LongPomo/LongPomo.xcodeproj -sdk ios  -configuration Debug -enableCodeCoverage YES build test
  - xcodebuild -scheme LongPomo-watch -project LongPomo/LongPomo.xcodeproj -sdk watchkit  -configuration Debug -enableCodeCoverage YES build
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'LongPomo'