language: swift # or objective-c
osx_image: xcode8.3simfix
script:
  - xcodebuild -scheme LongPomo -project LongPomo/LongPomo.xcodeproj -sdk macosx  -configuration Debug -enableCodeCoverage YES build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'LongPomo'